### ISSUE TITLE
Tests fail on Windows (Travis)

### ISSUE THREAD

**Issue by hackergrrl** [noffle/multi-hypercore-index#6]
See https://travis-ci.org/kappa-db/multifeed-index/builds/547432048

```
C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:313
        throw er
        ^
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\travis\AppData\Local\Temp\hyperdb-index-test-9124641999621466\0'
    at Object.rmdirSync (fs.js:684:3)
    at rmkidsSync (C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (C:\Users\travis\build\kappa-db\multifeed-index\node_modules\rimraf\rimraf.js:304:9)
    at Indexer.<anonymous> (C:\Users\travis\build\kappa-db\multifeed-index\test\adder.js:422:14)
```

**Comment by hackergrrl** [comment]
Fixed. Windows was failing to `rm -rf` because the multifeed hadn't been closed.
