### ISSUE TITLE
Buffer not correctly initialised when deserialising state

### ISSUE THREAD

**Issue by m4gpi** [noffle/multi-hypercore-index#8]
Hey kappa-crew! :smiley_cat: 

When [trying to initialise `kappa-view-list` with a `level` instance](https://github.com/KGibb8/kappa-db-exercises/blob/master/kappa-chat.js) rather than `memdb`, I'm getting the following:

```
/home/kyphae/Projects/kappalog/node_modules/multifeed-index/lib/state.js:38
  var len = buf.readUInt32LE(0)
                ^

TypeError: buf.readUInt32LE is not a function
    at Object.deserializeState [as deserialize] (/home/kyphae/Projects/kappalog/node_modules/multifeed-index/lib/state.js:38:17)
    at /home/kyphae/Projects/kappalog/node_modules/multifeed-index/index.js:71:23
    at /home/kyphae/Projects/kappa-view-list/index.js:111:14
    at /home/kyphae/Projects/kappalog/node_modules/levelup/lib/levelup.js:166:5
    at /home/kyphae/Projects/kappalog/node_modules/level-packager/node_modules/encoding-down/index.js:56:5
```

It appears when reading back state from the `.ldb` file, its not correctly deserialising because its not passing through a buffer obj.

Resolved in PR here: https://github.com/kappa-db/multifeed-index/pull/7

**Comment by m4gpi** [comment]
This is probably a better solution, fix in `kappa-view-level`: https://github.com/kappa-db/kappa-view-list/pull/4
